import React from 'react';
import './App.css';
import CoffeeList from './CoffeeList';
import "./tailwind.output.css"

function App() {
  return (
  <div className="flex-row items-center justify-between p-5">
    <div className="flex-1 flex-row">
      <h2 className="text-2xl leading-7 text-gray-900 sm:text-3xl sm:truncate">
        AWS Copilot Coffee ☕️        
      </h2>
      <span className="text-gray-500">Demo of ECS with Fargate using AWS Copilot CLI. <br/> 🚀 Build. 🚚 Release. 🔍 Monitor.</span>     
    </div>
    <CoffeeList></CoffeeList>
    <div className="fixed bottom-0 pb-3">
      Font generated by <a href="https://www.flaticon.com">flaticon.com</a>. Under <a href="http://creativecommons.org/licenses/by/3.0/">CC</a>: <a data-file="009-tea-cup" href="http://www.freepik.com">Freepik</a>, <a data-file="002-latte" href="https://www.flaticon.com/authors/smashicons">Smashicons</a>     
    </div>
  </div>
  );
}

export default App;
